### ISSUE TITLE
Unhandled IO errors

### ISSUE THREAD

**Issue by jstefanop** [Optiminer/OptiminerZcash#21]
Need to handle IO/pool coms errors better. Currently miner just stops mining if there is an I/O error or connection is dropped. Miner should be checking connection and keep attempting to reconnect to pool if there is an issue. 

[2017-01-09 16:19:25.638] [info] Concurrent write detected, queuing.
[2017-01-09 16:19:25.859] [warning] The write deadline expired! Closing connection.
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.859] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-09 16:19:25.861] [info] GPU2 Waiting for work from pool.
[2017-01-09 16:19:25.869] [info] GPU1 Waiting for work from pool.
[2017-01-09 16:19:25.880] [info] Connecting to us1-zcash.flypool.org:3333.
[2017-01-09 16:19:25.882] [info] GPU5 Waiting for work from pool.
[2017-01-09 16:19:25.892] [info] GPU0 Waiting for work from pool.
[2017-01-09 16:19:25.896] [info] GPU3 Waiting for work from pool.
[2017-01-09 16:19:25.901] [info] GPU4 Waiting for work from pool.
[2017-01-09 16:19:45.894] [error] No such host: us1-zcash.flypool.org(Host not found (non-authoritative), try again later)

**Comment by Optiminer** [comment]
Should be fixed in 1.3.2. Please test and close bug if confirmed.

**Comment by jstefanop** [comment]
@Optiminer Same issue still happening, this time instead of program crashing, it keeps mining but all shares submited return with IO/Error

[2017-01-12 19:04:12.472] [info] [GPU0]  135.0 I/s 254.0 S/s (5s) 135.2 I/s 255.4 S/s (1m) 135.7 I/s 254.8 S/s (1h)
[2017-01-12 19:04:13.165] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-12 19:04:13.644] [info] [GPU2]  129.0 I/s 229.2 S/s (5s) 130.4 I/s 244.2 S/s (1m) 130.7 I/s 245.6 S/s (1h)
[2017-01-12 19:04:13.854] [info] [GPU1]  128.0 I/s 229.8 S/s (5s) 129.8 I/s 243.8 S/s (1m) 130.7 I/s 245.4 S/s (1h)
[2017-01-12 19:04:14.498] [info] [GPU3]  131.0 I/s 255.8 S/s (5s) 130.4 I/s 249.4 S/s (1m) 130.8 I/s 246.1 S/s (1h)
[2017-01-12 19:04:15.604] [info] [GPU4]  130.0 I/s 244.4 S/s (5s) 130.2 I/s 242.3 S/s (1m) 130.4 I/s 245.2 S/s (1h)
[2017-01-12 19:04:17.090] [info] [GPU5]  133.0 I/s 240.8 S/s (5s) 132.2 I/s 249.2 S/s (1m) 132.6 I/s 248.7 S/s (1h)
[2017-01-12 19:04:17.456] [info] [Total]  789.0 I/s 1458.4 S/s (5s) 788.4 I/s 1481.8 S/s (1m) 791.1 I/s 1485.8 S/s (1h)
[2017-01-12 19:04:17.506] [info] [GPU0]  135.0 I/s 250.4 S/s (5s) 135.2 I/s 254.4 S/s (1m) 135.7 I/s 254.8 S/s (1h)
[2017-01-12 19:04:18.424] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-12 19:04:18.646] [info] [GPU2]  131.0 I/s 238.8 S/s (5s) 130.3 I/s 243.8 S/s (1m) 130.7 I/s 245.6 S/s (1h)
[2017-01-12 19:04:18.868] [info] [GPU1]  130.0 I/s 232.2 S/s (5s) 129.9 I/s 242.9 S/s (1m) 130.7 I/s 245.4 S/s (1h)
[2017-01-12 19:04:19.529] [info] [GPU3]  131.0 I/s 248.4 S/s (5s) 130.6 I/s 248.9 S/s (1m) 130.8 I/s 246.1 S/s (1h)
[2017-01-12 19:04:19.604] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-12 19:04:19.895] [error] IO/Error communicating to us1-zcash.flypool.org
[2017-01-12 19:04:20.631] [info] [GPU4]  130.0 I/s 249.4 S/s (5s) 130.1 I/s 242.3 S/s (1m) 130.4 I/s 245.2 S/s (1h)

**Comment by Optiminer** [comment]
Please try version 1.5.0

**Comment by phobosq** [comment]
I am running 1.5.0 from simplemining.net OS build, was successful for days with single 470, after adding another 480 yesterday and running for 5 hours I got this:
[2017-02-01 03:08:28.242] [warning] The write deadline expired! Closing connection.
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.243] [error] IO/Error communicating to eu1-zcash.flypool.org
[2017-02-01 03:08:28.281] [info] [GPU1] 146.0 I/s 274.4 S/s (5s) 146.6 I/s 275.4 S/s (1m) 146.6 I/s 274.8 S/s (1h)

The rig responds to ping, but miner process seems stuck.

**Comment by dlehenky** [comment]
It's very likely there is/was a external network problem between you and the pool. Why does this have to be a miner problem? There a lot going on between your home router and the pool, not to mention the pool itself (like a DDOS, server failover, etc.). Just saying ...

**Comment by Optiminer** [comment]
Version 1.6.0 fixes a segfault that caused the miner to crash sometimes when reconnecting.
