### ISSUE TITLE
[error] Found device with 32-bit addressing

### ISSUE THREAD

**Issue by DavBE** [Optiminer/OptiminerZcash#33]
Hi,

Getting this with 1.6  :

```
[2017-02-03 11:31:41.727] [error] Found device with 32-bit addressing. You need to set the environment variable 'GPU_FORCE_64BIT_PTR=1'!
```

GPU_FORCE_64BIT_PTR is set :

```
davbe@rig01 ~/optiminer-zcash-1.6.0 $ env | grep GPU
GPU_FORCE_64BIT_PTR=1
```

Any idea ?

**Comment by Optiminer** [comment]
Please show me the output of the --list-devices flag. 

This is probably related to the miner trying to use non-AMD platforms. Try specifying -c X on the command line where you try 0,1,2 for X.

**Comment by DavBE** [comment]
-c 0 did the trick

FYI here's the output of  --list-devices  :

```
[2017-02-03 13:13:50.873] [info] Optiminer/Zcash 1.6.0 (C) Optiminer 2017
Platform (-c) 0, Device (-d) 0:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.7 (VM)
  Address bits: 64
  Available memory: 8447557632
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 1:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.7 (VM)
  Address bits: 64
  Available memory: 4237635584
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 2:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.7 (VM)
  Address bits: 64
  Available memory: 4237635584
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 3:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.7 (VM)
  Address bits: 64
  Available memory: 4237635584
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 0, Device (-d) 4:
  Platform Vendor: AMD
  Device Name: Ellesmere
  Driver Version: 2117.7 (VM)
  Address bits: 64
  Available memory: 4237635584
  GCN Support: Gen 4
  Has device specific faster kernel: Yes
Platform (-c) 1, Device (-d) 0:
  Platform Vendor: Unknown
  Device Name: AMD POLARIS10 (DRM 3.3.0 / 4.8.0-26-generic, LLVM 3.8.1)
  Driver Version: 12.0.3
  Address bits: 32
  Available memory: 1073741824
Platform (-c) 1, Device (-d) 1:
  Platform Vendor: Unknown
  Device Name: AMD POLARIS10 (DRM 3.3.0 / 4.8.0-26-generic, LLVM 3.8.1)
  Driver Version: 12.0.3
  Address bits: 32
  Available memory: 1073741824
Platform (-c) 1, Device (-d) 2:
  Platform Vendor: Unknown
  Device Name: AMD POLARIS10 (DRM 3.3.0 / 4.8.0-26-generic, LLVM 3.8.1)
  Driver Version: 12.0.3
  Address bits: 32
  Available memory: 1073741824
Platform (-c) 1, Device (-d) 3:
  Platform Vendor: Unknown
  Device Name: AMD POLARIS10 (DRM 3.3.0 / 4.8.0-26-generic, LLVM 3.8.1)
  Driver Version: 12.0.3
  Address bits: 32
  Available memory: 1073741824
Platform (-c) 1, Device (-d) 4:
  Platform Vendor: Unknown
  Device Name: AMD POLARIS10 (DRM 3.3.0 / 4.8.0-26-generic, LLVM 3.8.1)
  Driver Version: 12.0.3
  Address bits: 32
  Available memory: 1073741824
```

**Comment by Optiminer** [comment]
Should be fixed in 1.6.1, that is also run without the -c.

**Comment by gr33k** [comment]
hey I'm on 1.7.0 with Radeon HD 5770 (2) getting the same error - Environment variable is set but can't get it to top that error.
-c 0 doesn't resolve it -c 1,2,3 says "No matching devices! quitting!"
